include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_catches_without_on_clauses: true
    avoid_function_literals_in_foreach_calls: false
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    avoid_setters_without_getters: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true

    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: false
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    library_names: true
    library_prefixes: true
    no_logic_in_create_state: false
    non_constant_identifier_names: true
    one_member_abstracts: false
    only_throw_errors: true
    overridden_fields: false
    parameter_assignments: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_function_declarations_over_variables: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_mixin: true
    prefer_relative_imports: false
    prefer_single_quotes: false

    require_trailing_commas: false
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    slash_for_doc_comments: false
    sort_child_properties_last: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    use_colored_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    avoid_redundant_argument_values: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

dart_code_metrics:
  rules:
    avoid-commented-out-code: true
    avoid-empty-setstate: true
    avoid-expanded-as-spacer: true
    avoid-missing-image-alt: true
    avoid-ref-read-inside-build: true
    avoid-ref-watch-outside-build: true
    avoid-shrink-wrap-in-lists: true
    avoid-single-child-column-or-row: true
    avoid-unnecessary-consumer-widgets: true
    avoid-unnecessary-stateful-widgets: true
    prefer-container: true
    prefer-correct-edge-insets-constructor: true
    prefer-dedicated-media-query-methods: true
    prefer-sized-box-square: true
    prefer-spacing: true
    unnecessary_async: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
